version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - 8080:80
    volumes:
     - ../:/var/www/html
    depends_on:
      - mysqldb

  mysqldb:
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysqldb:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tudai
      

  myadmin:
    image: "phpmyadmin/phpmyadmin"
    environment:
      PMA_HOST: mysqldb
      PMA_USER: root
      PMA_PASSWORD: tudai
    ports:
      - 8081:80
    depends_on:
      - mysqldb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080
    depends_on:
      - mysqldb
